// v3/services/ui/src/views/Login.vue
<script setup lang="ts">
import { ref } from "vue";
import { useRouter } from "vue-router";
import { useAuthStore } from "../stores/auth";
import { ApiError } from "../api/client";

const auth = useAuthStore();
const router = useRouter();

const username = ref("");
const password = ref("");
const error = ref<string | null>(null);
const submitting = ref(false);

async function submit() {
  error.value = null;
  submitting.value = true;
  try {
    const resp = await auth.login({ username: username.value, password: password.value });
    if (resp.password_must_change) {
      await router.push("/change-password");
    } else {
      await router.push("/jobs");
    }
  } catch (e) {
    error.value =
      e instanceof ApiError && e.status === 401
        ? "Invalid username or password"
        : e instanceof Error
          ? e.message
          : "Login failed";
  } finally {
    submitting.value = false;
  }
}
</script>

<template>
  <div class="center-screen">
    <form class="card login-card" @submit.prevent="submit">
      <h2 style="margin-top: 0">Sign in to ARM</h2>
      <div class="field">
        <label for="username">Username</label>
        <input id="username" v-model="username" autocomplete="username" autofocus />
      </div>
      <div class="field">
        <label for="password">Password</label>
        <input
          id="password"
          v-model="password"
          type="password"
          autocomplete="current-password"
        />
      </div>
      <p v-if="error" class="error">{{ error }}</p>
      <button :disabled="submitting || !username || !password" type="submit">
        {{ submitting ? "Signing in…" : "Sign in" }}
      </button>
      <p class="muted" style="margin-top: 16px; font-size: 12px">
        First-boot default is <code>admin</code> / <code>admin</code>. You'll
        be required to change it before anything else loads.
      </p>
    </form>
  </div>
</template>

// services/ui-neu/frontend/src/routes/login/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { login } from '$lib/api/auth';
	import { applyLogin } from '$lib/stores/auth';

	let username = $state('');
	let password = $state('');
	let error = $state('');
	let submitting = $state(false);

	async function onSubmit(e: Event) {
		e.preventDefault();
		if (submitting) return;
		submitting = true;
		error = '';
		try {
			const result = await login(username, password);
			applyLogin(result);
			goto(result.password_must_change ? '/change-password' : '/');
		} catch (err) {
			error = err instanceof Error ? err.message : 'Login failed';
		} finally {
			submitting = false;
		}
	}
</script>

<div class="flex min-h-screen items-center justify-center p-4">
	<form onsubmit={onSubmit} class="w-full max-w-sm space-y-4 rounded-lg border border-primary/20 bg-surface p-6 dark:bg-surface-dark">
		<h1 class="text-lg font-semibold">Sign in to ARM</h1>
		{#if error}
			<p class="rounded bg-red-100 px-3 py-2 text-sm text-red-700 dark:bg-red-900/30 dark:text-red-300">{error}</p>
		{/if}
		<label class="block text-sm">
			<span class="mb-1 block">Username</span>
			<input bind:value={username} required autocomplete="username" class="w-full rounded border border-primary/20 px-3 py-2 dark:bg-surface-dark" />
		</label>
		<label class="block text-sm">
			<span class="mb-1 block">Password</span>
			<input bind:value={password} type="password" required autocomplete="current-password" class="w-full rounded border border-primary/20 px-3 py-2 dark:bg-surface-dark" />
		</label>
		<button type="submit" disabled={submitting} class="w-full rounded bg-primary px-4 py-2 font-medium text-white disabled:opacity-60">
			{submitting ? 'Signing in...' : 'Sign in'}
		</button>
	</form>
</div>
