// v3/services/ui/src/views/SessionForm.vue
<script setup lang="ts">
import { computed, onMounted, ref, watch } from "vue";
import { useRoute, useRouter } from "vue-router";
import { ApiError } from "../api/client";
import { useRipPresetsStore } from "../stores/ripPresets";
import { useSessionsStore } from "../stores/sessions";
import { useTranscodePresetsStore } from "../stores/transcodePresets";
import type { MediaType, SessionView } from "../api/types";

const route = useRoute();
const router = useRouter();
const sessions = useSessionsStore();
const ripPresets = useRipPresetsStore();
const tcPresets = useTranscodePresetsStore();

const editing = computed(() => typeof route.params.id === "string");
const editId = computed(() => (editing.value ? (route.params.id as string) : null));

const name = ref("");
const mediaType = ref<MediaType>("movie");
const ripPresetId = ref("");
const transcodePresetId = ref<string | "">("");
const template = ref("");
const isBuiltin = ref(false);

const error = ref<string | null>(null);
const saving = ref(false);
const previewText = ref("");
const previewError = ref<string | null>(null);
let previewTimer: number | null = null;

const filteredRipPresets = computed(() => ripPresets.byMediaType(mediaType.value));
const filteredTranscodePresets = computed(() => tcPresets.byMediaType(mediaType.value));

onMounted(async () => {
  await Promise.all([ripPresets.fetchAll(), tcPresets.fetchAll()]);
  if (editing.value && editId.value) {
    try {
      const s: SessionView = await sessions.getById(editId.value);
      name.value = s.name;
      mediaType.value = s.media_type;
      ripPresetId.value = s.rip_preset_id;
      transcodePresetId.value = s.transcode_preset_id ?? "";
      template.value = s.output_path_template;
      isBuiltin.value = s.is_builtin;
    } catch (e) {
      error.value = e instanceof ApiError ? e.message : "Failed to load";
    }
  }
});

watch([template, mediaType, transcodePresetId], () => {
  if (previewTimer !== null) window.clearTimeout(previewTimer);
  if (!template.value) {
    previewText.value = "";
    previewError.value = null;
    return;
  }
  previewTimer = window.setTimeout(async () => {
    try {
      const resp = await sessions.previewTemplate({
        template: template.value,
        media_type: mediaType.value,
        has_transcode_preset: Boolean(transcodePresetId.value),
      });
      previewText.value = resp.expansion;
      previewError.value = null;
    } catch (e) {
      previewText.value = "";
      previewError.value = e instanceof ApiError ? e.message : "Preview failed";
    }
  }, 300);
});

async function save(): Promise<void> {
  saving.value = true;
  error.value = null;
  try {
    if (editing.value && editId.value) {
      const payload = isBuiltin.value
        ? { name: name.value }
        : {
            name: name.value,
            rip_preset_id: ripPresetId.value,
            transcode_preset_id: transcodePresetId.value || null,
            output_path_template: template.value,
          };
      await sessions.update(editId.value, payload);
    } else {
      await sessions.create({
        name: name.value,
        media_type: mediaType.value,
        rip_preset_id: ripPresetId.value,
        transcode_preset_id: transcodePresetId.value || null,
        output_path_template: template.value,
      });
    }
    await router.push("/sessions");
  } catch (e) {
    error.value = e instanceof ApiError ? e.message : "Save failed";
  } finally {
    saving.value = false;
  }
}
</script>

<template>
  <h2>{{ editing ? "Edit session" : "New session" }}</h2>
  <p v-if="isBuiltin" class="muted">
    This is a built-in session — only the name can be edited. Use <strong>Clone</strong> from the
    list to customise the rest.
  </p>
  <p v-if="error" class="error">{{ error }}</p>
  <form class="card" style="max-width: 720px" @submit.prevent="save">
    <div class="field">
      <label for="name">Name</label>
      <input id="name" v-model="name" required />
    </div>

    <div class="field">
      <label for="media-type">Media type</label>
      <select id="media-type" v-model="mediaType" :disabled="editing">
        <option value="movie">Movie</option>
        <option value="tv">TV</option>
        <option value="music">Music</option>
        <option value="data">Data</option>
        <option value="iso">ISO</option>
      </select>
    </div>

    <div class="field">
      <label for="rip-preset">Rip preset</label>
      <select id="rip-preset" v-model="ripPresetId" :disabled="isBuiltin" required>
        <option value="" disabled>Choose…</option>
        <option v-for="p in filteredRipPresets" :key="p.id" :value="p.id">
          {{ p.name }}{{ p.is_builtin ? " (built-in)" : "" }}
        </option>
      </select>
    </div>

    <div class="field">
      <label for="tc-preset">Transcode preset</label>
      <select id="tc-preset" v-model="transcodePresetId" :disabled="isBuiltin">
        <option value="">(none)</option>
        <option v-for="p in filteredTranscodePresets" :key="p.id" :value="p.id">
          {{ p.name }}{{ p.is_builtin ? " (built-in)" : "" }}
        </option>
      </select>
    </div>

    <div class="field">
      <label for="template">Output path template</label>
      <input id="template" v-model="template" :disabled="isBuiltin" required />
      <p v-if="previewText" class="muted" style="margin-top: 4px; font-size: 12px">
        Preview: <code>{{ previewText }}</code>
      </p>
      <p v-else-if="previewError" class="error" style="margin-top: 4px; font-size: 12px">
        {{ previewError }}
      </p>
    </div>

    <div class="row" style="gap: 8px">
      <button type="submit" :disabled="saving || !name || (!isBuiltin && (!ripPresetId || !template))">
        {{ saving ? "Saving…" : "Save" }}
      </button>
      <RouterLink to="/sessions"><button class="secondary" type="button">Cancel</button></RouterLink>
    </div>
  </form>
</template>

// services/ui-neu/frontend/src/lib/components/SessionForm.svelte
<script lang="ts">
	// Ported from services/ui/src/views/SessionForm.vue, structured like the
	// sibling RipPresetForm/TranscodePresetForm. Inline (no-route) form.
	// media_type immutable on edit; built-in is name-only. Loads rip + transcode
	// preset lists for the dropdowns, filtered to the form's media_type (the
	// backend requires preset.media_type == session.media_type). Live debounced
	// /preview under the template field. overrides_json is NEVER sent (a seeded
	// value must survive an edit untouched).
	import { onMount, onDestroy } from 'svelte';
	import { createSession, updateSession, previewTemplate } from '$lib/api/sessions';
	import { fetchRipPresets } from '$lib/api/ripPresets';
	import { fetchTranscodePresets } from '$lib/api/transcodePresets';
	import type {
		MediaType,
		RipPresetView,
		SessionView,
		TranscodePresetView
	} from '$lib/types/api.gen';

	let {
		session = null,
		onsaved,
		oncancel
	}: {
		session?: SessionView | null;
		onsaved: (s: SessionView) => void;
		oncancel: () => void;
	} = $props();

	const editing = $derived(!!session);
	const isBuiltin = $derived(session?.is_builtin ?? false);

	let name = $state(session?.name ?? '');
	let mediaType = $state<MediaType>(session?.media_type ?? 'movie');
	let ripPresetId = $state(session?.rip_preset_id ?? '');
	let transcodePresetId = $state(session?.transcode_preset_id ?? '');
	let template = $state(session?.output_path_template ?? '');

	let ripPresets = $state<RipPresetView[]>([]);
	let transcodePresets = $state<TranscodePresetView[]>([]);

	let submitting = $state(false);
	let error = $state<string | null>(null);

	let previewText = $state('');
	let previewError = $state<string | null>(null);
	let previewTimer: ReturnType<typeof setTimeout> | null = null;

	const ripOptions = $derived(ripPresets.filter((p) => p.media_type === mediaType));
	const transcodeOptions = $derived(transcodePresets.filter((p) => p.media_type === mediaType));
	const canSubmit = $derived(!submitting && name.trim().length > 0 && ripPresetId.length > 0);

	onMount(async () => {
		[ripPresets, transcodePresets] = await Promise.all([fetchRipPresets(), fetchTranscodePresets()]);
		if (!ripPresetId) ripPresetId = ripOptions[0]?.id ?? '';
		runPreview();
	});

	onDestroy(() => {
		if (previewTimer !== null) clearTimeout(previewTimer);
	});

	// When media_type changes (create mode only — disabled on edit), drop any
	// now-invalid preset selection so submit can't 400 on a media_type mismatch.
	function onMediaTypeChange(): void {
		if (!ripPresets.some((p) => p.media_type === mediaType && p.id === ripPresetId)) {
			ripPresetId = ripOptions[0]?.id ?? '';
		}
		if (!transcodePresets.some((p) => p.media_type === mediaType && p.id === transcodePresetId))
			transcodePresetId = '';
		runPreview();
	}

	function schedulePreview(): void {
		if (previewTimer !== null) clearTimeout(previewTimer);
		previewTimer = setTimeout(runPreview, 300);
	}

	async function runPreview(): Promise<void> {
		if (!template) {
			previewText = '';
			previewError = null;
			return;
		}
		try {
			const resp = await previewTemplate({
				template,
				media_type: mediaType,
				has_transcode_preset: Boolean(transcodePresetId)
			});
			previewText = resp.expansion;
			previewError = null;
		} catch (e) {
			previewText = '';
			previewError = e instanceof Error ? e.message : 'Preview failed';
		}
	}

	async function submit(event: Event): Promise<void> {
		event.preventDefault();
		if (!canSubmit) return;
		submitting = true;
		error = null;
		try {
			let result: SessionView;
			if (editing && session) {
				if (isBuiltin) {
					result = await updateSession(session.id, { name });
				} else {
					// Custom edit: no media_type (immutable), no overrides_json (preserve).
					result = await updateSession(session.id, {
						name,
						rip_preset_id: ripPresetId,
						transcode_preset_id: transcodePresetId || null,
						output_path_template: template
					});
				}
			} else {
				result = await createSession({
					name,
					media_type: mediaType,
					rip_preset_id: ripPresetId,
					transcode_preset_id: transcodePresetId || null,
					output_path_template: template
				});
			}
			onsaved(result);
		} catch (e) {
			error = e instanceof Error ? e.message : 'Save failed';
		} finally {
			submitting = false;
		}
	}

	const labelClass = 'text-sm font-medium text-gray-700 dark:text-gray-300';
	const inputClass =
		'mt-1 w-full rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm text-gray-900 disabled:cursor-not-allowed disabled:opacity-50 dark:border-gray-600 dark:bg-gray-800 dark:text-white';
</script>

<form class="space-y-4" onsubmit={submit}>
	<h3 class="text-lg font-semibold text-gray-900 dark:text-white">
		{editing ? 'Edit session' : 'New session'}
	</h3>

	{#if isBuiltin}
		<p class="text-sm text-gray-500 dark:text-gray-400" data-testid="session-builtin-note">
			Built-in preset - only the name is editable. Clone it to customise.
		</p>
	{/if}

	{#if error}
		<p class="text-sm text-red-600 dark:text-red-400" data-testid="session-error">{error}</p>
	{/if}

	<div>
		<label class={labelClass} for="session-name">Name</label>
		<input
			id="session-name"
			data-testid="session-name"
			type="text"
			required
			bind:value={name}
			disabled={submitting}
			class={inputClass}
		/>
	</div>

	<div>
		<label class={labelClass} for="session-media-type">Media type</label>
		<select
			id="session-media-type"
			data-testid="session-media-type"
			bind:value={mediaType}
			onchange={onMediaTypeChange}
			disabled={editing}
			class={inputClass}
		>
			<option value="movie">Movie</option>
			<option value="tv">TV</option>
			<option value="music">Music</option>
			<option value="data">Data</option>
			<option value="iso">ISO</option>
		</select>
	</div>

	<div>
		<label class={labelClass} for="session-rip-preset">Rip preset</label>
		<select
			id="session-rip-preset"
			data-testid="session-rip-preset"
			bind:value={ripPresetId}
			disabled={isBuiltin}
			required
			class={inputClass}
		>
			{#each ripOptions as p (p.id)}
				<option value={p.id}>{p.name}</option>
			{/each}
		</select>
	</div>

	<div>
		<label class={labelClass} for="session-transcode-preset">Transcode preset (optional)</label>
		<select
			id="session-transcode-preset"
			data-testid="session-transcode-preset"
			bind:value={transcodePresetId}
			onchange={schedulePreview}
			disabled={isBuiltin}
			class={inputClass}
		>
			<option value="">- none -</option>
			{#each transcodeOptions as p (p.id)}
				<option value={p.id}>{p.name}</option>
			{/each}
		</select>
	</div>

	<div>
		<label class={labelClass} for="session-template">Output path template</label>
		<input
			id="session-template"
			data-testid="session-template"
			type="text"
			required
			bind:value={template}
			oninput={schedulePreview}
			disabled={isBuiltin}
			class={inputClass}
		/>
		{#if previewError}
			<p class="mt-1 rounded-md border border-red-300 bg-red-50 px-2.5 py-1.5 font-mono text-xs text-red-700 dark:border-red-700 dark:bg-red-900/20 dark:text-red-400" data-testid="session-preview-error">
				{previewError}
			</p>
		{:else if previewText}
			<p class="mt-1 rounded-md border-l-2 border-primary bg-primary/5 px-2.5 py-1.5 font-mono text-xs text-primary-text dark:text-primary-text-dark" data-testid="session-preview">
				▸ {previewText}
			</p>
		{/if}
	</div>

	<div class="flex justify-end gap-3 pt-2">
		<button
			type="button"
			onclick={oncancel}
			disabled={submitting}
			class="rounded-lg px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-700"
		>
			Cancel
		</button>
		<button
			type="submit"
			disabled={!canSubmit}
			data-testid="session-submit"
			class="rounded-lg px-4 py-2 text-sm font-medium confirm-btn-primary disabled:cursor-not-allowed disabled:opacity-50"
		>
			{submitting ? 'Saving...' : 'Save'}
		</button>
	</div>
</form>
