// services/ui-neu/frontend/src/lib/components/RipPresetForm.svelte
<script lang="ts">
	// Ported from services/ui/src/views/RipPresetForm.vue. The Vue view is a
	// routed page; this is an inline (no-route) form driven by props. Field
	// wiring, the disabled rules, and the create / custom-edit / built-in
	// submit-body shapes follow the Vue source faithfully.
	import { createRipPreset, updateRipPreset } from '$lib/api/ripPresets';
	import TrackFiltersEditor from './TrackFiltersEditor.svelte';
	import type {
		IdentificationMode,
		MediaType,
		OutputMode,
		RipPresetView,
		TrackSelection
	} from '$lib/types/api.gen';

	type TrackFilters = {
		min_duration_seconds?: number | null;
		max_duration_seconds?: number | null;
		title_indices?: number[] | null;
		title_indices_exclude?: number[] | null;
	};

	let {
		preset = null,
		onsaved,
		oncancel
	}: {
		preset?: RipPresetView | null;
		onsaved: (p: RipPresetView) => void;
		oncancel: () => void;
	} = $props();

	const editing = $derived(!!preset);
	const isBuiltin = $derived(preset?.is_builtin ?? false);

	// Seed from the preset on edit, or the create-defaults otherwise.
	let name = $state(preset?.name ?? '');
	let mediaType = $state<MediaType>(preset?.media_type ?? 'movie');
	let trackSelection = $state<TrackSelection>(preset?.track_selection ?? 'main_feature');
	let identificationMode = $state<IdentificationMode>(
		preset?.identification_mode ?? 'required'
	);
	let outputMode = $state<OutputMode>(preset?.output_mode ?? 'tracks');
	let filters = $state<TrackFilters>((preset?.track_filters_json as TrackFilters) ?? {});

	let submitting = $state(false);
	let error = $state<string | null>(null);

	const showFilters = $derived(trackSelection === 'custom' && !isBuiltin);
	const canSubmit = $derived(!submitting && name.trim().length > 0);

	// Mirrors the Vue source: only send a track_filters_json object for the
	// custom selection, and drop null/undefined keys from it; otherwise null.
	function buildTrackFilters(): TrackFilters | null {
		if (trackSelection !== 'custom') return null;
		return Object.fromEntries(
			Object.entries(filters).filter(([, v]) => v !== null && v !== undefined)
		) as TrackFilters;
	}

	async function submit(event: Event): Promise<void> {
		event.preventDefault();
		if (!canSubmit) return;
		submitting = true;
		error = null;
		try {
			let result: RipPresetView;
			if (editing && preset) {
				if (isBuiltin) {
					// Built-in presets: only the name is mutable.
					result = await updateRipPreset(preset.id, { name });
				} else {
					// Custom edit: no media_type (immutable after create).
					result = await updateRipPreset(preset.id, {
						name,
						track_selection: trackSelection,
						identification_mode: identificationMode,
						output_mode: outputMode,
						track_filters_json: buildTrackFilters()
					});
				}
			} else {
				result = await createRipPreset({
					name,
					media_type: mediaType,
					track_selection: trackSelection,
					identification_mode: identificationMode,
					output_mode: outputMode,
					track_filters_json: buildTrackFilters()
				});
			}
			onsaved(result);
		} catch (e) {
			error = e instanceof Error ? e.message : 'Save failed';
		} finally {
			submitting = false;
		}
	}

	const labelClass = 'text-sm font-medium text-gray-700 dark:text-gray-300';
	const inputClass =
		'mt-1 w-full rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm text-gray-900 disabled:cursor-not-allowed disabled:opacity-50 dark:border-gray-600 dark:bg-gray-800 dark:text-white';
</script>

<form class="space-y-4" onsubmit={submit}>
	<h3 class="text-lg font-semibold text-gray-900 dark:text-white">
		{editing ? 'Edit rip preset' : 'New rip preset'}
	</h3>

	{#if isBuiltin}
		<p class="text-sm text-gray-500 dark:text-gray-400" data-testid="preset-builtin-note">
			Built-in preset - only the name is editable.
		</p>
	{/if}

	{#if error}
		<p class="text-sm text-red-600 dark:text-red-400" data-testid="preset-error">{error}</p>
	{/if}

	<div>
		<label class={labelClass} for="preset-name">Name</label>
		<input
			id="preset-name"
			data-testid="preset-name"
			type="text"
			required
			bind:value={name}
			disabled={submitting}
			class={inputClass}
		/>
	</div>

	<div>
		<label class={labelClass} for="preset-media-type">Media type</label>
		<select
			id="preset-media-type"
			data-testid="preset-media-type"
			bind:value={mediaType}
			disabled={editing}
			class={inputClass}
		>
			<option value="movie">Movie</option>
			<option value="tv">TV</option>
			<option value="music">Music</option>
			<option value="data">Data</option>
			<option value="iso">ISO</option>
		</select>
	</div>

	<div>
		<label class={labelClass} for="preset-track-selection">Track selection</label>
		<select
			id="preset-track-selection"
			data-testid="preset-track-selection"
			bind:value={trackSelection}
			disabled={isBuiltin}
			class={inputClass}
		>
			<option value="main_feature">Main feature (longest ≥ 45 min)</option>
			<option value="all_tracks">All tracks (≥ 60 s)</option>
			<option value="archive">Archive (every track)</option>
			<option value="custom">Custom</option>
		</select>
	</div>

	<div>
		<label class={labelClass} for="preset-identification-mode">Identification mode</label>
		<select
			id="preset-identification-mode"
			data-testid="preset-identification-mode"
			bind:value={identificationMode}
			disabled={isBuiltin}
			class={inputClass}
		>
			<option value="required">Required</option>
			<option value="skip">Skip</option>
			<option value="deferred_placeholder">Deferred placeholder</option>
		</select>
	</div>

	<div>
		<label class={labelClass} for="preset-output-mode">Output mode</label>
		<select
			id="preset-output-mode"
			data-testid="preset-output-mode"
			bind:value={outputMode}
			disabled={isBuiltin}
			class={inputClass}
		>
			<option value="tracks">Tracks</option>
			<option value="iso">ISO</option>
			<option value="data_copy">Data copy</option>
		</select>
	</div>

	{#if showFilters}
		<TrackFiltersEditor value={filters} onchange={(v) => (filters = v)} />
	{/if}

	<div class="flex justify-end gap-3 pt-2">
		<button
			type="button"
			onclick={oncancel}
			disabled={submitting}
			class="rounded-lg px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-700"
		>
			Cancel
		</button>
		<button
			type="submit"
			disabled={!canSubmit}
			data-testid="preset-submit"
			class="rounded-lg px-4 py-2 text-sm font-medium confirm-btn-primary disabled:cursor-not-allowed disabled:opacity-50"
		>
			{submitting ? 'Saving...' : 'Save'}
		</button>
	</div>
</form>

// v3/services/ui/src/views/RipPresetForm.vue
<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import { ApiError } from "../api/client";
import TrackFiltersEditor from "../components/TrackFiltersEditor.vue";
import { useRipPresetsStore } from "../stores/ripPresets";
import type {
  IdentificationMode,
  MediaType,
  OutputMode,
  RipPresetView,
  TrackFilters,
  TrackSelection,
} from "../api/types";

const route = useRoute();
const router = useRouter();
const ripPresets = useRipPresetsStore();

const editing = computed(() => typeof route.params.id === "string");
const editId = computed(() => (editing.value ? (route.params.id as string) : null));

const name = ref("");
const mediaType = ref<MediaType>("movie");
const trackSelection = ref<TrackSelection>("main_feature");
const identificationMode = ref<IdentificationMode>("required");
const outputMode = ref<OutputMode>("tracks");
const filters = ref<TrackFilters>({});
const isBuiltin = ref(false);

const error = ref<string | null>(null);
const saving = ref(false);

onMounted(async () => {
  if (editing.value && editId.value) {
    try {
      const p: RipPresetView = await ripPresets.getById(editId.value);
      name.value = p.name;
      mediaType.value = p.media_type;
      trackSelection.value = p.track_selection;
      identificationMode.value = p.identification_mode;
      outputMode.value = p.output_mode;
      filters.value = p.track_filters_json ?? {};
      isBuiltin.value = p.is_builtin;
    } catch (e) {
      error.value = e instanceof ApiError ? e.message : "Failed to load";
    }
  }
});

async function save(): Promise<void> {
  saving.value = true;
  error.value = null;
  try {
    const trackFilters =
      trackSelection.value === "custom"
        ? Object.fromEntries(
            Object.entries(filters.value).filter(([, v]) => v !== null && v !== undefined),
          )
        : null;
    if (editing.value && editId.value) {
      const payload = isBuiltin.value
        ? { name: name.value }
        : {
            name: name.value,
            track_selection: trackSelection.value,
            identification_mode: identificationMode.value,
            output_mode: outputMode.value,
            track_filters_json: trackFilters as TrackFilters | null,
          };
      await ripPresets.update(editId.value, payload);
    } else {
      await ripPresets.create({
        name: name.value,
        media_type: mediaType.value,
        track_selection: trackSelection.value,
        identification_mode: identificationMode.value,
        output_mode: outputMode.value,
        track_filters_json: trackFilters as TrackFilters | null,
      });
    }
    await router.push("/rip-presets");
  } catch (e) {
    error.value = e instanceof ApiError ? e.message : "Save failed";
  } finally {
    saving.value = false;
  }
}
</script>

<template>
  <h2>{{ editing ? "Edit rip preset" : "New rip preset" }}</h2>
  <p v-if="isBuiltin" class="muted">Built-in preset — only the name is editable.</p>
  <p v-if="error" class="error">{{ error }}</p>
  <form class="card" style="max-width: 720px" @submit.prevent="save">
    <div class="field">
      <label>Name</label>
      <input v-model="name" required />
    </div>
    <div class="field">
      <label>Media type</label>
      <select v-model="mediaType" :disabled="editing">
        <option value="movie">Movie</option>
        <option value="tv">TV</option>
        <option value="music">Music</option>
        <option value="data">Data</option>
        <option value="iso">ISO</option>
      </select>
    </div>
    <div class="field">
      <label>Track selection</label>
      <select v-model="trackSelection" :disabled="isBuiltin">
        <option value="main_feature">Main feature (longest ≥ 45 min)</option>
        <option value="all_tracks">All tracks (≥ 60 s)</option>
        <option value="archive">Archive (every track)</option>
        <option value="custom">Custom</option>
      </select>
    </div>
    <div class="field">
      <label>Identification mode</label>
      <select v-model="identificationMode" :disabled="isBuiltin">
        <option value="required">Required</option>
        <option value="skip">Skip</option>
        <option value="deferred_placeholder">Deferred placeholder</option>
      </select>
    </div>
    <div class="field">
      <label>Output mode</label>
      <select v-model="outputMode" :disabled="isBuiltin">
        <option value="tracks">Tracks</option>
        <option value="iso">ISO</option>
        <option value="data_copy">Data copy</option>
      </select>
    </div>
    <TrackFiltersEditor v-if="trackSelection === 'custom' && !isBuiltin" v-model="filters" />
    <div class="row" style="gap: 8px; margin-top: 12px">
      <button type="submit" :disabled="saving || !name">{{ saving ? "Saving…" : "Save" }}</button>
      <RouterLink to="/rip-presets"><button class="secondary" type="button">Cancel</button></RouterLink>
    </div>
  </form>
</template>
